### ISSUE TITLE
Ghost Shot + Haemolacria does not work like other synergies

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#10]
![image](https://user-images.githubusercontent.com/81973147/125706300-c0d380bf-dc8c-4340-9346-cc3820729b4f.png)
![image](https://user-images.githubusercontent.com/81973147/125706340-20d9dfd2-9c69-4046-acfd-52c572793cab.png)
you should be shooting a big glob then when it touches the ground ghost shots should come out

**Comment by Crinfarr** [comment]
seems like a pretty easy fix

**Comment by KyojoH** [comment]
fixed in commit bc06186a37b61128bf14106396ad62af84032021
