### ISSUE TITLE
Rerolling + removing Ghost Shot does not work properly

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#11]
When you enter a new room after you did one of those it gives it back
![image](https://user-images.githubusercontent.com/81973147/125706494-3736837f-58a9-413f-8bf9-eb05ce5f73b7.png)
![image](https://user-images.githubusercontent.com/81973147/125706505-dc9e9ae3-5290-47d0-b5e1-bef43d2e5e98.png)

**Comment by KyojoH** [comment]
fixed but don't remember what commit it was
