### ISSUE TITLE
Fat Fetus is invisable 

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#13]
![image](https://user-images.githubusercontent.com/81973147/125706644-23e0c58d-0957-47fc-b03c-56e3108e9d97.png)
the bomb wont show when you shoot it

**Comment by KyojoH** [comment]
still?!

**Comment by KyojoH** [comment]
fixed in commit e03acd34a961387654dafbf85fc9e26ab50d7d6f
