### ISSUE TITLE
Ghost Shot makes a lot of mess

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#15]
![image](https://user-images.githubusercontent.com/81973147/125706775-0272da27-5cce-4dd2-8181-6818e42a8d8b.png)
ghost shot pierces so when its in something it creates blood until it disappears/enemy dies

![image](https://user-images.githubusercontent.com/81973147/125706909-5c0724b4-6219-4db7-9954-4ec9d833d17f.png)

**Comment by AndreDoruk** [comment]
should we close this? i mean it doesnt make a mess anymore

**Comment by KyojoH** [comment]
yep
