### ISSUE TITLE
Ghost shot + Trisagion sometimes spawns stationary trisagion shots that stay until the room is left

### ISSUE THREAD

**Issue by Crinfarr** [AndreDoruk/Forgotten-Fables#16]
![image](https://user-images.githubusercontent.com/31548109/125735857-fee65a2b-c411-42c7-a648-caf6da2e30ab.png)

**Comment by AndreDoruk** [comment]
I think this is normal as Trisagion + Pop works like this too

**Comment by Crinfarr** [comment]
fixed in `b740f0`
