### ISSUE TITLE
Stone D6 lets you pickup shop/devil deal items for free

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#18]
![image](https://user-images.githubusercontent.com/81973147/125784850-cb05538a-cd42-43ac-873f-7530a3e06858.png)
![image](https://user-images.githubusercontent.com/81973147/125784985-52da26dd-5eee-4715-859d-1c1f03b1486c.png)

**Comment by Crinfarr** [comment]
from @blippsk:

> stone d6 allows you to pick up both/all choice pedestals when rerolled (hush room, options, more options, etc)
