### ISSUE TITLE
Ghost Shot's shot is upside down

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#2]
![image](https://user-images.githubusercontent.com/81973147/125703278-3eab172d-4222-4843-8715-4f16745f5860.png)

**Comment by KyojoH** [comment]
Commit a5f4fb9 fixed this

**Comment by AndreDoruk** [comment]
![image](https://user-images.githubusercontent.com/81973147/125787020-06f41de9-8554-4f52-bd91-8d4275858300.png)
when shooting left its correct 

![image](https://user-images.githubusercontent.com/81973147/125787051-b995b705-d972-4fc7-915f-32a90c6e7b0d.png)
shooting right makes it upsidedown

![image](https://user-images.githubusercontent.com/81973147/125787104-488b4cc6-00d5-4046-ad8b-571cb8e56dc1.png)
up

![image](https://user-images.githubusercontent.com/81973147/125787136-deb3c2b6-c831-40f9-9968-6954738630c4.png)
down

**Comment by Crinfarr** [comment]
[fixed](https://github.com/AndreDoruk/Forgotten-Fables/commit/ce14ba642ffa50f8a7c64e0150b2f189c817ce95)
