### ISSUE TITLE
Changed Ghost Shot aoe explossion to Purgatory aoe explosion affect

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#22]
Make it the circle explosion instead a full ass explosion
![image](https://user-images.githubusercontent.com/81973147/125786213-c8bea9d3-30f7-400f-afe6-592ca777bd0b.png)

these two?
![shockwave](https://user-images.githubusercontent.com/81973147/125786312-bd7f7cf1-50d1-4576-aa63-2d642e9d9714.png)
![spooky_ghosts](https://user-images.githubusercontent.com/81973147/125786319-ed460206-7b1b-45e1-a32b-008abc2dee28.png)

**Comment by paltham** [comment]
yes, make it a circle explosion

**Comment by KyojoH** [comment]
Fixed in commit 46dab6f7e13634206de89dd21ae118db6a7153a0
