### ISSUE TITLE
Add Ghost Shots tail like what Purgatory has

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#23]
@KyojoH you

**Comment by Crinfarr** [comment]
this is in the sprite if I read it right, it might only be possible to implement in shaders but it wouldn't look great

**Comment by KyojoH** [comment]
Yeah, looking at the game's resources, it looks like it's hardcoded. Since the tail curves with the homing 'head', it will be very difficult if not impossible to implement with the current API.
