### ISSUE TITLE
Ghost Shot tear size wont scale 

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#24]
![image](https://user-images.githubusercontent.com/81973147/125786536-3f344e08-e4b0-4ccb-8d7d-b518ec6bc4d6.png)
i have poly but the tear size is the same as without it

**Comment by Crinfarr** [comment]
[fixed](https://github.com/AndreDoruk/Forgotten-Fables/commit/ce14ba642ffa50f8a7c64e0150b2f189c817ce95)
