### ISSUE TITLE
Ghost Shot + Mom's knife cant shoot

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#25]
![image](https://user-images.githubusercontent.com/81973147/125805308-85d27e16-a38b-4b94-83bf-ca567b3f0244.png)
you cant shoot with this combo

**Comment by Crinfarr** [comment]
Should we make a synergy or just make knife override

**Comment by AndreDoruk** [comment]
maybe it just gives it slight homing and aoe?

**Comment by KyojoH** [comment]
Fixed in commit b7f86e39d26731130e61f4f95333e363b3ec1724
