### ISSUE TITLE
Everyone only has blackhearts now

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#27]
with the mod
![image](https://user-images.githubusercontent.com/81973147/125938630-540bea30-bb3f-4fd7-b180-76cab35973f4.png)

without the mod
![image](https://user-images.githubusercontent.com/81973147/125938637-aaad3f05-998f-4345-bf98-191192e46c87.png)

this is with everyone

**Comment by KyojoH** [comment]
Aagh

**Comment by KyojoH** [comment]
Fixed in commit 2d1a92d84a0c0c2104c2350f7f1f45b61043b527
