### ISSUE TITLE
Alabaster can have Angel room spawn

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#28]
![image](https://user-images.githubusercontent.com/81973147/125946059-b890ca39-c6ed-4ea8-975b-8985ce3b9088.png)
![image](https://user-images.githubusercontent.com/81973147/125946075-4c220610-5629-4d04-a213-ac1708829d28.png)

**Comment by Crinfarr** [comment]
nvm this fix crashes the game sometimes

**Comment by Crinfarr** [comment]
We're just gonna ignore this and rework the entire character because the API runs on 2 hamster wheels
