### ISSUE TITLE
Ghost Shot/Blood Drive should not be able to be rerolled while playing as alabaster

### ISSUE THREAD

**Issue by paltham** [AndreDoruk/Forgotten-Fables#33]

**Comment by KyojoH** [comment]
For blood drive I just need to add the "quest" tag in items.xml. For ghost shot will have to find something else, probably just make the effect happen as alabaster without giving him(her?them?it?) the actual item.

**Comment by KyojoH** [comment]
fixed in commit 9a050751f919ab9efb99aa2cd273f6493f2a560a
