### ISSUE TITLE
Alabaster can have red health

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#5]
Alabaster can not have red health

**Comment by KyojoH** [comment]
commit 1377e5e fixed it

**Comment by KyojoH** [comment]
commit 305fd69 fixed it

**Comment by AndreDoruk** [comment]
![image](https://user-images.githubusercontent.com/81973147/125946419-ee2ebb0f-33a3-4b0b-ad75-d3dd5ab6f954.png)
![image](https://user-images.githubusercontent.com/81973147/125946439-398e35ad-9424-49df-bde4-c406b39475c4.png)
alabaster can have red health with bone hearts which other soul heart only characters cant

**Comment by Crinfarr** [comment]
fixed in `6a1d6b4`
