### ISSUE TITLE
Costumes give Alabaster white skin and sometimes legs

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#6]
Alabaster is pink and whenever an item with a costume (that changes your skin(?)) gets picked Alabaster turns white
and sometimes gives you legs
![image](https://user-images.githubusercontent.com/81973147/125704037-3a993b65-4f42-4776-8d0c-71022f5c8682.png)
![image](https://user-images.githubusercontent.com/81973147/125704270-aeb03046-c043-47d9-9ef8-199cbebb61d6.png)
![image](https://user-images.githubusercontent.com/81973147/125704325-763ce52f-ad66-4457-8d38-5d5bcfcff708.png)

**Comment by KyojoH** [comment]
Doesn't happen anymore, my guess is commit 9c9595ce64558aa28a0f089cd71b23117fea1020 fixed it since I changed the skin tag in players.xml
