### ISSUE TITLE
Blue Heart wont give soul hearts

### ISSUE THREAD

**Issue by AndreDoruk** [AndreDoruk/Forgotten-Fables#9]
Blue hearts wont give soul hearts until you kill the boss then it spawns 3 soul hearts in the middle of the room
![image](https://user-images.githubusercontent.com/81973147/125706003-26d03c11-0bf6-40b4-9c48-587be6af0dfc.png)

from console
![image](https://user-images.githubusercontent.com/81973147/125706061-42e6704e-7fcb-41e9-a40b-432e1d5e29b5.png)

**Comment by KyojoH** [comment]
fixed in commit 8ecf0c224dc3cf75e08044140aaab1de10732bb7
